name: Auto update get methods

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  main:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
