name: Auto update get methods

on:
  schedule:
    - cron:  '25 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
