name: Auto update get methods with dependabot

on:
  push:
    branches:
      - 'dependabot/bundler/google-ads-googleads-**'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Generate new list file of deprecated get methods
        run: bin/deprecated_methods_generator
      - name: Check diff, commit and push
        run: |
          git config --local user.email "hanocha.peter@gmail.com"
          git config --local user.name "hanocha"
          git add lib/rubocop/cop/google_ads/deprecated_get_methods.yml
          if git commit -m 'Generate new list file of deprecated get methods'; then
            git push
          fi
