name: Auto update get methods

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  main:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: Install dependencies
        run: bundle install
